### ISSUE TITLE
I don't find the code that adding gaussian noise to ground-truth instance kernel

### ISSUE THREAD

**Issue by MaverickRen** [chenhaoxing/DiffusionInst#1]
In the formula of the paper, you added gaussian noise to ground-truth kernel, but I did not find the generation of ground-truth kernel in the code, and the sampling process like DDPM, does this conform to the paradigm of diffusion model? The prediction of the bounding box offset in DiffusionDet can still be understood as denoising, but I found that in your code, the generation of the kernel is directly predicted with the ROI feature, and there is no denoising process. Maybe my understanding is wrong, I hope you can help me solve my doubts, Thank you.

**Comment by zhangxgu** [comment]
@MaverickRen 
Hi, in the caption of figure 2, we said "During training, we add random t step noise to the groundtruth boxes and pad them to predefined numbers. Instance-aware noisy filters are constructed by combining features and noisy boxes. " 
Actually, the noisy instance filter is generated by noisy boxes and features. Thus, the adding noise and  DDIM are now all based on bounding boxes. It is like "adding noise to gt_Box for noisy instance diffusion scheme". 
We are now working on directly add noise to the instance itself.
 By now, we will add an equation from noisy boxes to noisy instances to fix this error and update arxiv in a few days.

**Comment by MaverickRen** [comment]
Thank you for your reply, and look forward to your further improvement




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenhaoxing/DiffusionInst"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月7日(星期三) 晚上6:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chenhaoxing/DiffusionInst] I don't find the code that adding gaussian noise to ground-truth instance kernel (Issue #1)





 
@MaverickRen
 Hi, in the caption of figure 2, we said "During training, we add random t step noise to the groundtruth boxes and pad them to predefined numbers. Instance-aware noisy filters are constructed by combining features and noisy boxes. "
 Actually, the noisy instance filter is generated by noisy boxes and features. Thus, the adding noise and  DDIM are now all based on bounding boxes. It is like "adding noise to gt_Box for noisy instance diffusion scheme".
 We are now working on directly add noise to the instance itself.
 By now, we will add an equation from noisy boxes to noisy instances to fix this error and update arxiv in a few days.
