### ISSUE TITLE
evaluate on test-dev set

### ISSUE THREAD

**Issue by pinecho** [chenhaoxing/DiffusionInst#10]
Hello! I noticed that your model was evaluated on the COCO test-dev set. However, it appears that the COCO codalab server is no longer active and displays the message "Submission upload has been disabled. See the new instance at: https://codalab.lisn.upsaclay.fr/". Unfortunately, the new link is not accepting any submissions at this time. Can you please provide more information about how you were able to evaluate your model on the test-dev set? Thank you!

**Comment by zhangxgu** [comment]
Hi, you can use this url:
https://codalab.lisn.upsaclay.fr/competitions/7383#learn_the_details

**Comment by pinecho** [comment]
Thank you so much!
