### ISSUE TITLE
Pre-trained Weights

### ISSUE THREAD

**Issue by selinkoles** [chenhaoxing/DiffusionInst#12]
Hi, 
The link you provided here is not working. Can you please help?
"We now provide trained models for ResNet-50 and ResNet-101.
https://pan.baidu.com/s/1KEdjNY3CSXWp0VFwkhRKYg, pwd: jhbv."

**Comment by zhangxgu** [comment]
Hi, this url is for the diffusioninst after trained, which can be evaluated on COCO. If you are finding pretrained weights, they are in the getting-started doc. 
See:
3. Prepare pretrain models
DiffusionInst uses three backbones including ResNet-50, ResNet-101 and Swin-Base. The pretrained ResNet-50 model can be downloaded automatically by Detectron2.

[DiffusionDet](https://github.com/ShoufaChen/DiffusionDet) provide pretrained [ResNet-101](https://github.com/ShoufaChen/DiffusionDet/releases/download/v0.1/torchvision-R-101.pkl) and [Swin-Base](https://github.com/ShoufaChen/DiffusionDet/releases/download/v0.1/swin_base_patch4_window7_224_22k.pkl) which are compatible with Detectron2. Please download them to DiffusionInst_ROOT/models/ before training.

**Comment by selinkoles** [comment]
Thank you for your quick response, however i can't even open the provided links above as ResNet-101 and SwinBase and ResNet-50. And are these weighrs for COCO or LVIS?

**Comment by zhangxgu** [comment]
Sorry for this problem. We have fixed it. You can try it.

**Comment by selinkoles** [comment]
Thankss, so these are for COCO or LVIS? And do I need pth file to train/evaluate the model or can i use directly pkl file you uploaded now?

**Comment by zhangxgu** [comment]
The pretrained weights are utilized for both two datasets. To train our model, you should load the pre-trained weights. If you only want to evaluate our model, you can load the trained model for only evaluation.
