### ISSUE TITLE
Are the weights for COCO 1 step/ 4 step?

### ISSUE THREAD

**Issue by talhayaseen57** [chenhaoxing/DiffusionInst#14]
The weights provided in the [https://pan.baidu.com/s/1KEdjNY3CSXWp0VFwkhRKYg](https://pan.baidu.com/s/1KEdjNY3CSXWp0VFwkhRKYg), are these weights for COCO step 1 or COCO step 4?

**Comment by zhangxgu** [comment]
@talhayaseen57 
The difference between step 1 or step 4 is how many times for denoising during inference phase.  They share a same trained weight.

**Comment by talhayaseen57** [comment]
@zhangxgu! I have another question:
while using demo to see the results, does denoising have any effect at the results. such I am using following command and changing `MODEL.DiffusionInst.SAMPLE_STEP 4` to `1`.
```
python demo.py --config-file configs/diffinst.coco.res101.yaml --input image3.jpg --confidence-threshold 0.35 --output ./figure/ResNet101/image3step4_0.35.jpg --opts MODEL.WEIGHTS ./pretrained_weights/diffusioninst_res101.pth MODEL.DiffusionInst.SAMPLE_STEP 4
```
