### ISSUE TITLE
File not found error while evaluating on lvis dataset

### ISSUE THREAD

**Issue by ankitgoyalumd** [chenhaoxing/DiffusionInst#20]
Hi, I am trying to run inference on lvis dataset.

I downloaded lvis_val.json under datasets/lvis folder. 
I am running evaluation using the command below:
`!python train_net.py --num-gpus 1 --config-file configs/diffinst.lvis.swinbase.yaml --eval-only MODEL.WEIGHTS DiffusionInst_ROOT/models/swin_base_patch4_window7_224_22k.pkl`

I am running into following error:

`FileNotFoundError: [Errno 2] No such file or directory: 'datasets/coco/train2017/000000000009.jpg'
`
It is confusing why it is trying to access coco dataset when I am using config file for Lvis. Please advise. I am stuck here for quite sometime.

**Comment by zhangxgu** [comment]
Hi, 
the lvis dataset is based on the images from COCO. LVIS use many long-tail object annotations to test the detection and instance segmentation ability of different models.
