### ISSUE TITLE
download diffinst_coco_res50.pth

### ISSUE THREAD

**Issue by xinxiyaaa** [chenhaoxing/DiffusionInst#9]
Hello, I would like to ask where I can download diffinst_coco_res50.pth

**Comment by zhangxgu** [comment]
Sorry for the late response. The diffinst_coco_res50.pth is the trained weights. We will upload the weights soon

**Comment by abhigoku10** [comment]
@zhangxgu @chenhaoxing  can you please upload the weight on the google drive or one drive as baidu is not avaialble ?
THanks  in adavance

**Comment by selinkoles** [comment]
> @zhangxgu @chenhaoxing can you please upload the weight on the google drive or one drive as baidu is not avaialble ? THanks in adavance

Hi! If you could find other pretrained weights, can you pls guide to access them?
